# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lecturer', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('native_place', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=30)),
                ('posting_place', models.CharField(max_length=30)),
                ('MDFF', models.CharField(max_length=30)),
                ('ST', models.CharField(max_length=30)),
                ('OJT', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateField()),
                ('ending', models.DateField()),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ONGC_A.Week'),
        ),
    ]
