# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
        migrations.AddField(
            model_name='student',
            name='MDFF',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='OJT',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ST',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='designation',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='native_place',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='posting_place',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
