# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neel', '0007_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neel.Lecture')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
